{
 "title": "Evidently Dashboard",
 "description": "Some evidently metrics",
 "time": { "from": "now-120d", "to": "now" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", num_drifted_columns AS \"value\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Shared Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", share_missing_values AS \"value\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Quantile 0.5 for fare_amount column",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", quantile_0_5_fare_amount AS \"value\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pearson Correlation between 'fare_amount' and 'trip_distance' columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", pearson_corr_fare_amount AS \"value\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  }
 ]
}